name: Feature request
description: Suggest an idea for CurlPyPro
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      placeholder: "When I test my API I have to ... which is slow because ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
